export enum Topic {
  Updated,
  Moved,
  Loaded,
  SelectionChanged,
  SelectionMoving,
  SelectionMoved,
  Resizing,
  Resized,
  DragEnd,
  ResizeModelUpdated,
  StartMove,
  Moving,
  EndMove,
  PropertyEditorUpdated,
  PropertyChanged,
  AssistLinesChanged,
  EditMode
}